# Titanic: Machine Learning from Disaster

### Pré-processamento e análise dos dados

In [1]:
import pandas as pd
import numpy as np

# importing the dataset
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
train.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [3]:
train.describe(include = 'all')

PassengerId    Survived      Pclass  \
count    891.000000  891.000000  891.000000   
unique          NaN         NaN         NaN   
top             NaN         NaN         NaN   
freq            NaN         NaN         NaN   
mean     446.000000    0.383838    2.308642   
std      257.353842    0.486592    0.836071   
min        1.000000    0.000000    1.000000   
25%      223.500000    0.000000    2.000000   
50%      446.000000    0.000000    3.000000   
75%      668.500000    1.000000    3.000000   
max      891.000000    1.000000    3.000000   

                                             Name   Sex         Age  \
count                                         891   891  714.000000   
unique                                        891     2         NaN   
top     Stone, Mrs. George Nelson (Martha Evelyn)  male         NaN   
freq                                            1   577         NaN   
mean                                          NaN   NaN   29.699118   
std                                           NaN   NaN   14.526497   
min                                           NaN   NaN    0.420000   
25%                                           NaN   NaN   20.125000   
50%                                           NaN   NaN   28.000000   
75%                                           NaN   NaN   38.000000   
max                                           NaN   NaN   80.000000   

             SibSp       Parch Ticket        Fare        Cabin Embarked  
count   891.000000  891.000000    891  891.000000          204      889  
unique         NaN         NaN    681         NaN          147        3  
top            NaN         NaN   1601         NaN  C23 C25 C27        S  
freq           NaN         NaN      7         NaN            4      644  
mean      0.523008    0.381594    NaN   32.204208          NaN      NaN  
std       1.102743    0.806057    NaN   49.693429          NaN      NaN  
min       0.000000    0.000000    NaN    0.000000          NaN      NaN  
25%       0.000000    0.000000    NaN    7.910400          NaN      NaN  
50%       0.000000    0.000000    NaN   14.454200          NaN      NaN  
75%       1.000000    0.000000    NaN   31.000000          NaN      NaN  
max       8.000000    6.000000    NaN  512.329200          NaN      NaN

In [4]:
survivors = train[train.Survived == 1]
total_survivors = survivors['PassengerId'].size

print('Passengers that survived: ' + str(total_survivors))

survivors

Passengers that survived: 342


PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
15            16         1       2   
17            18         1       2   
19            20         1       3   
21            22         1       2   
22            23         1       3   
23            24         1       1   
25            26         1       3   
28            29         1       3   
31            32         1       1   
32            33         1       3   
36            37         1       3   
39            40         1       3   
43            44         1       2   
44            45         1       3   
47            48         1       3   
52            53         1       1   
53            54         1       2   
55            56         1       1   
56            57         1       2   
58            59         1       2   
61            62         1       1   
65            66         1       3   
66            67         1       2   
..           ...       ...     ...   
809          810         1       1   
820          821         1       1   
821          822         1       3   
823          824         1       3   
827          828         1       2   
828          829         1       3   
829          830         1       1   
830          831         1       3   
831          832         1       2   
835          836         1       1   
838          839         1       3   
839          840         1       1   
842          843         1       1   
849          850         1       1   
853          854         1       1   
855          856         1       3   
856          857         1       1   
857          858         1       1   
858          859         1       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
869          870         1       3   
871          872         1       1   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex    Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.00      1   
2                               Heikkinen, Miss. Laina  female  26.00      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.00      1   
11                            Bonnell, Miss. Elizabeth  female  58.00      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0   
17                        Williams, Mr. Charles Eugene    male    NaN      0   
19                             Masselmani, Mrs. Fatima  female    NaN      0   
21                               Beesley, Mr. Lawrence    male  34.00      0   
22                         McGowan, Miss. Anna "Annie"  female  15.00      0   
23                        Sloper, Mr. William Thompson    male  28.00      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.00      1   
28                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0   
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1   
32                            Glynn, Miss. Mary Agatha  female    NaN      0   
36                                    Mamee, Mr. Hanna    male    NaN      0   
39                         Nicola-Yarred, Miss. Jamila  female  14.00      1   
43            Laroche, Miss. Simonne Marie Anne 

In [5]:
train.groupby('Sex').agg({'Survived': np.average, 'Age' : np.average, 'SibSp' : np.average, 'Parch' : np.average})

Survived  Age     SibSp     Parch
Sex                                      
female  0.742038  NaN  0.694268  0.649682
male    0.188908  NaN  0.429809  0.235702

In [6]:
train.dropna(0).groupby('Sex').agg({'Age' : np.average})

Age
Sex              
female  32.676136
male    38.451789

In [7]:
survivors.loc[:, ('Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked')].mode()

Pclass     Sex   Age  SibSp  Parch Ticket  Fare    Cabin Embarked
0       1  female  24.0      0      0   1601  13.0  B96 B98        S

In [8]:
survivors.groupby('Sex').agg({'Survived': np.average, 'Age' : np.average, 'SibSp' : np.average, 'Parch' : np.average})

Survived  Age     SibSp     Parch
Sex                                      
female         1  NaN  0.515021  0.515021
male           1  NaN  0.385321  0.357798

In [9]:
survivors.dropna().groupby('Sex').agg({'Age' : np.average})

Age
Sex              
female  33.054878
male    32.607805

In [10]:
colunas = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
first_survivors = survivors.loc[survivors.Pclass == 1, colunas]

first_survivors.mode()

Pclass     Sex   Age  SibSp  Parch  Ticket   Fare    Cabin Embarked
0       1  female  35.0      0      0  113760  26.55  B96 B98        S

In [11]:
female_survivors = survivors.loc[survivors.Sex == 'female', colunas]

female_survivors.mode()

Pclass     Sex   Age  SibSp  Parch Ticket  Fare Cabin Embarked
0     1.0  female  24.0    0.0    0.0   2666  13.0  E101        S
1     NaN     NaN   NaN    NaN    NaN    NaN  26.0   F33      NaN

### Criando um modelo

### Teste 1

Naive Bayes

Atributos aparentemente decisivos para a sobrevivência do passageiro:

    • sexo (convertido para números: 1 - feminino e 2 - masculino)
    
    • classe (1ª, 2ª, 3ª)
    
    • cônjuges, irmãos (SibSp)
    
    • pais, filhos (Parch)

In [12]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn import metrics

dataset = train.loc[:, ('PassengerId', 'Sex', 'Pclass', 'SibSp', 'Parch', 'Survived')]

#Female = 1 | Male = 2
dataset.loc[:, 'Sex'] = dataset.loc[:, 'Sex'].apply(lambda sex: 1 if sex == 'female' else 2)

#índice causa erro no Naive Bayes
#dataset.set_index('PassengerId', inplace = True)

print(f'Dataset (treino): {dataset.shape}')

dataset.head()

Dataset (treino): (891, 6)


PassengerId  Sex  Pclass  SibSp  Parch  Survived
0            1    2       3      1      0         0
1            2    1       1      1      0         1
2            3    1       3      0      0         1
3            4    1       1      1      0         1
4            5    2       3      0      0         0

In [13]:
model = GaussianNB()

data = dataset.loc[:, dataset.columns[:5]]
target = dataset.loc[:, dataset.columns[5]]
        
model.fit(data, target)
    
data = dataset.loc[:, dataset.columns[:5]]
target = dataset.loc[:, dataset.columns[5]]
    
predicted = model.predict(data)

print(metrics.classification_report(target, predicted))
print(metrics. confusion_matrix(target, predicted))

k = 5
i = 1

print(f'{k} folds\n\n')

kfold = KFold(n_splits = k, shuffle = False)

for i_train, i_test in kfold.split(dataset):
    data = dataset.loc[i_train, dataset.columns[:5]]
    target = dataset.loc[i_train, dataset.columns[5]]
        
    model.fit(data, target)
    
    data = dataset.loc[i_test, dataset.columns[:5]]
    target = dataset.loc[i_test, dataset.columns[5]]
    
    predicted = model.predict(data)
    
    print(f'\n\nFold #{i} | train: {len(dataset.iloc[i_train])}, test: {len(dataset.iloc[i_test])}')
    print(metrics.classification_report(target, predicted))
    print(metrics.confusion_matrix(target, predicted))
    
    i += 1

              precision    recall  f1-score   support

           0       0.85      0.76      0.80       549
           1       0.67      0.79      0.73       342

   micro avg       0.77      0.77      0.77       891
   macro avg       0.76      0.77      0.76       891
weighted avg       0.78      0.77      0.77       891

[[415 134]
 [ 71 271]]
5 folds




Fold #1 | train: 712, test: 179
              precision    recall  f1-score   support

           0       0.84      0.71      0.77       120
           1       0.55      0.73      0.63        59

   micro avg       0.72      0.72      0.72       179
   macro avg       0.70      0.72      0.70       179
weighted avg       0.75      0.72      0.72       179

[[85 35]
 [16 43]]


Fold #2 | train: 713, test: 178
              precision    recall  f1-score   support

           0       0.80      0.75      0.77        99
           1       0.71      0.76      0.73        79

   micro avg       0.75      0.75      0.75       178
   macro

In [14]:
dataset = test.loc[:, ('PassengerId', 'Sex', 'Pclass', 'SibSp', 'Parch')]

#Female = 1 | Male = 2
dataset.loc[:, 'Sex'] = dataset.loc[:, 'Sex'].apply(lambda sex: 1 if sex == 'female' else 2)

print(f'Dataset (teste): {dataset.shape}')

dataset.head()

Dataset (teste): (418, 5)


PassengerId  Sex  Pclass  SibSp  Parch
0          892    2       3      0      0
1          893    1       3      1      0
2          894    2       2      0      0
3          895    2       3      0      0
4          896    1       3      1      1

In [15]:
predicted = model.predict(dataset)

predicted

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [16]:
test['Survived'] = predicted

test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [17]:
result = test.loc[:, ('PassengerId', 'Survived')]
result.to_csv("gender_submission.csv", sep = ",", index = False)
result

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         1
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         1
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

#### Resultado

0.75598

### Teste 2

Naive Bayes

Atributos aparentemente decisivos para a sobrevivência do passageiro:

    • sexo (convertido para números: 1 - feminino e 2 - masculino)
    
    • cônjuges, irmãos (SibSp)
    
    • pais, filhos (Parch)
    
    • idade (possui NAs que serão trocados pela moda da idade dos sobreviventes)

In [18]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
survivors = train[train.Survived == 1]

survivors.loc[:, 'Sex'] = survivors.loc[:, 'Sex'].apply(lambda s: 1 if s == 'female' else 2)

idade_moda = float(survivors.Age.mode())
survivors.loc[:, 'Age'] = survivors.loc[:, 'Age'].fillna(idade_moda)

survivors.head()

C:\Users\davir\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name  Sex   Age  SibSp  Parch  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1      0   

             Ticket     Fare Cabin Embarked  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
8            347742  11.1333   NaN        S  
9            237736  30.0708   NaN        C

In [20]:
dataset = train

dataset.loc[:, 'Sex'] = dataset.loc[:, 'Sex'].apply(lambda s: 1 if s == 'female' else 2)

dataset.loc[:, 'Age'] = dataset.loc[:, 'Age'].fillna(idade_moda)

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    2  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    2  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [21]:
colunas = ['Sex', 'Age', 'SibSp', 'Parch', 'Survived']

model = GaussianNB()

data = dataset.loc[:, colunas[:4]]
target = dataset.loc[:, colunas[4]]
        
model.fit(data, target)
    
data = dataset.loc[:, colunas[:4]]
target = dataset.loc[:, colunas[4]]
    
predicted = model.predict(data)

print(metrics.classification_report(target, predicted))
print(metrics. confusion_matrix(target, predicted))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       549
           1       0.77      0.66      0.71       342

   micro avg       0.80      0.80      0.80       891
   macro avg       0.79      0.77      0.78       891
weighted avg       0.80      0.80      0.79       891

[[483  66]
 [115 227]]


In [22]:
k = 5
i = 1

print(f'{k} folds\n\n')

kfold = KFold(n_splits = k, shuffle = False)

for i_train, i_test in kfold.split(dataset):
    data = dataset.loc[i_train, colunas[:4]]
    target = dataset.loc[i_train, colunas[4]]
        
    model.fit(data, target)
    
    data = dataset.loc[i_test, colunas[:4]]
    target = dataset.loc[i_test, colunas[4]]
    
    predicted = model.predict(data)
    
    print(f'\n\nFold #{i} | train: {len(dataset.iloc[i_train])}, test: {len(dataset.iloc[i_test])}')
    print(metrics.classification_report(target, predicted))
    print(metrics.confusion_matrix(target, predicted))
    
    i += 1

5 folds




Fold #1 | train: 712, test: 179
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       120
           1       0.73      0.68      0.70        59

   micro avg       0.81      0.81      0.81       179
   macro avg       0.79      0.78      0.78       179
weighted avg       0.81      0.81      0.81       179

[[105  15]
 [ 19  40]]


Fold #2 | train: 713, test: 178
              precision    recall  f1-score   support

           0       0.78      0.88      0.83        99
           1       0.82      0.70      0.75        79

   micro avg       0.80      0.80      0.80       178
   macro avg       0.80      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

[[87 12]
 [24 55]]


Fold #3 | train: 713, test: 178
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       109
           1       0.76      0.70      0.73        69

   micro avg       0.80     

In [23]:
dataset = test

dataset.loc[:, 'Sex'] = dataset.loc[:, 'Sex'].apply(lambda s: 1 if s == 'female' else 2)

dataset.loc[:, 'Age'] = dataset.loc[:, 'Age'].fillna(idade_moda)

dataset.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    2   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    2   
3          895       3                              Wirz, Mr. Albert    2   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [24]:
data = dataset.loc[:, colunas[:4]]
    
predicted = model.predict(data)

predicted

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [25]:
test['Survived'] = predicted

test.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    2   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    2   
3          895       3                              Wirz, Mr. Albert    2   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [26]:
result = test.loc[:, ('PassengerId', 'Survived')]
result.to_csv("gender_submission.csv", sep = ",", index = False)
result

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

#### Resultado

0.76555

### Teste 3

Naive Bayes

Utilizando todos os atributos, exceto ID e Nome:

    • sexo (convertido para números: 1 - feminino e 2 - masculino)
    
    • classe (1ª, 2ª, 3ª)
    
    • cônjuges, irmãos (SibSp)
    
    • pais, filhos (Parch)
    
    • idade (substituída pela média dos sobreviventes da classe, quando não informada)
    
    • ticket
    
    • fare
       
    • cabin (substituída pela moda dos sobreviventes da classe correspondente, quando não informada)

    • embarked (substituído pela moda dos sobreviventes da classe correspondente, quando não informado)

In [27]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [28]:
survivors = train[train.Survived == 1]

survivors.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [29]:
train.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [30]:
#idade: substituir NA pela média de idade da classe correspondente
medias = survivors.groupby('Pclass').median().reset_index()

idade_media = medias['Age']
idade_media.index = medias['Pclass']

#cabine: substituir pela moda da cabine da classe correspondente
cabin_moda = pd.Series([survivors.loc[survivors.Pclass == 1, 'Cabin'].mode()[0], 
                        survivors.loc[survivors.Pclass == 2, 'Cabin'].mode()[0],
                        survivors.loc[survivors.Pclass == 3, 'Cabin'].mode()[0]])
cabin_moda.index = medias['Pclass']

#A moda é o porto 'S' para todas as classes
embarked_moda = survivors.loc[:, 'Embarked'].mode()[0]

#fare: substituir pela média da classe correspondente
fare_media = medias['Fare']
fare_media.index = medias['Pclass']

medias

Pclass  PassengerId  Survived   Age  SibSp  Parch     Fare
0       1        510.5       1.0  35.0    0.0    0.0  77.9583
1       2        441.0       1.0  28.0    0.0    0.0  21.0000
2       3        359.0       1.0  22.0    0.0    0.0   8.5167

In [31]:
def tratar_dados(dataframe, idade_media, cabin_moda, embarked_moda):
    #sexo: 1 - feminino; 2 - masculino
    dataframe.loc[:, 'Sex'] = dataframe.Sex.apply(lambda s: 1 if s == 'female' else 2)
    
    #idade: substituir NA pela média de idade da classe correspondente    
    for i in range(1, 4):
        dataframe.loc[dataframe.Pclass == i, 'Age'] = dataframe.loc[dataframe.Pclass == i, 'Age'].fillna(idade_media[i])
    
    #cabine: substituir pela moda da cabine da classe correspondente e substituir texto por categorias numéricas (factorize)
    for i in range(1, 4):
        dataframe.loc[dataframe.Pclass == i, 'Cabin'] = dataframe.loc[dataframe.Pclass == i, 'Cabin'].fillna(cabin_moda[i])

    counts, uniques = pd.factorize(dataframe.Cabin)
    dataframe.loc[:, 'Cabin'] = counts
    
    #embarked: moda é o porto 'S' para todas as classes; substituir texto por categorias numéricas (factorize)
    dataframe.loc[:, 'Embarked'] = dataframe.loc[:, 'Embarked'].fillna(embarked_moda)
    
    counts, uniques = pd.factorize(dataframe.Embarked)
    dataframe.loc[:, 'Embarked'] = counts
    
    #fare: substituir NA pela média da classe correspondente    
    for i in range(1, 4):
        dataframe.loc[dataframe.Pclass == i, 'Fare'] = dataframe.loc[dataframe.Pclass == i, 'Fare'].fillna(fare_media[i])
    
    #ticket: substituir texto por categorias numéricas (factorize)
    counts, uniques = pd.factorize(dataframe.Ticket)
    dataframe.loc[:, 'Ticket'] = counts
    
    return dataframe

In [32]:
tratar_dados(survivors, idade_media, cabin_moda, embarked_moda)

survivors.count()

C:\Users\davir\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            342
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          342
Embarked       342
dtype: int64

In [33]:
dataset = train.copy()

tratar_dados(dataset, idade_media, cabin_moda, embarked_moda)

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    2  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    2  35.0      0      0   

   Ticket     Fare  Cabin  Embarked  
0       0   7.2500      0         0  
1       1  71.2833      1         1  
2       2   7.9250      0         0  
3       3  53.1000      2         0  
4       4   8.0500      0         0

In [34]:
colunas = ['Sex', 'Age', 'SibSp', 'Parch', 'Pclass', 'Ticket', 'Embarked', 'Fare', 'Cabin', 'Survived']

model = GaussianNB()

data = dataset.loc[:500, colunas[:9]]
target = dataset.loc[:500, colunas[9]]
        
model.fit(data, target)

data = dataset.loc[501:, colunas[:9]]
target = dataset.loc[501:, colunas[9]]

predicted = model.predict(data)

print(metrics.classification_report(target, predicted))
print(metrics.confusion_matrix(target, predicted))

              precision    recall  f1-score   support

           0       0.85      0.78      0.82       241
           1       0.69      0.78      0.73       149

   micro avg       0.78      0.78      0.78       390
   macro avg       0.77      0.78      0.77       390
weighted avg       0.79      0.78      0.78       390

[[189  52]
 [ 33 116]]


In [35]:
k = 50
i = 1

print(f'{k} folds\n\n')

kfold = KFold(n_splits = k, shuffle = False)

for i_train, i_test in kfold.split(dataset):
    data = dataset.loc[i_train, colunas[:9]]
    target = dataset.loc[i_train, colunas[9]]
        
    model.fit(data, target)
    
    data = dataset.loc[i_test, colunas[:9]]
    target = dataset.loc[i_test, colunas[9]]
    
    predicted = model.predict(data)
    
    print(f'\n\nFold #{i} | train: {len(dataset.iloc[i_train])}, test: {len(dataset.iloc[i_test])}')
    print(metrics.classification_report(target, predicted))
    print(metrics.confusion_matrix(target, predicted))
    
    i += 1

50 folds




Fold #1 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.88      0.78      0.82         9

   micro avg       0.83      0.83      0.83        18
   macro avg       0.84      0.83      0.83        18
weighted avg       0.84      0.83      0.83        18

[[8 1]
 [2 7]]


Fold #2 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.73      0.80      0.76        10
           1       0.71      0.62      0.67         8

   micro avg       0.72      0.72      0.72        18
   macro avg       0.72      0.71      0.71        18
weighted avg       0.72      0.72      0.72        18

[[8 2]
 [3 5]]


Fold #3 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.90      0.82      0.86        11
           1       0.75      0.86      0.80         7

   micro avg       0.83      0.83      0.8



Fold #23 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.85      0.79      0.81        14
           1       0.40      0.50      0.44         4

   micro avg       0.72      0.72      0.72        18
   macro avg       0.62      0.64      0.63        18
weighted avg       0.75      0.72      0.73        18

[[11  3]
 [ 2  2]]


Fold #24 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.64      0.70      0.67        10
           1       0.57      0.50      0.53         8

   micro avg       0.61      0.61      0.61        18
   macro avg       0.60      0.60      0.60        18
weighted avg       0.61      0.61      0.61        18

[[7 3]
 [4 4]]


Fold #25 | train: 873, test: 18
              precision    recall  f1-score   support

           0       0.56      0.71      0.63         7
           1       0.78      0.64      0.70        11

   micro avg       0.67      0.67      0.67   



Fold #48 | train: 874, test: 17
              precision    recall  f1-score   support

           0       0.91      0.83      0.87        12
           1       0.67      0.80      0.73         5

   micro avg       0.82      0.82      0.82        17
   macro avg       0.79      0.82      0.80        17
weighted avg       0.84      0.82      0.83        17

[[10  2]
 [ 1  4]]


Fold #49 | train: 874, test: 17
              precision    recall  f1-score   support

           0       0.89      0.80      0.84        10
           1       0.75      0.86      0.80         7

   micro avg       0.82      0.82      0.82        17
   macro avg       0.82      0.83      0.82        17
weighted avg       0.83      0.82      0.82        17

[[8 2]
 [1 6]]


Fold #50 | train: 874, test: 17
              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.75      1.00      0.86         6

   micro avg       0.88      0.88      0.88   

In [36]:
dataset = test.copy()

tratar_dados(dataset, idade_media, cabin_moda, embarked_moda)

dataset.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    2   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    2   
3          895       3                              Wirz, Mr. Albert    2   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch  Ticket     Fare  Cabin  Embarked  
0  34.5      0      0       0   7.8292      0         0  
1  47.0      1      0       1   7.0000      0         1  
2  62.0      0      0       2   9.6875      1         0  
3  27.0      0      0       3   8.6625      0         1  
4  22.0      1      1       4  12.2875      0         1

In [37]:
data = dataset.loc[:, colunas[:9]]

predicted = model.predict(data)

predicted

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [38]:
test['Survived'] = predicted

test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [39]:
result = test.loc[:, ('PassengerId', 'Survived')]
result.to_csv("gender_submission.csv", sep = ",", index = False)
result

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         1
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         1
405         1297         1
406         1298         0
407         1299         1
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

#### Resultado

0.74641

### Teste 4

Naive Bayes

Utilizando todos os atributos, exceto ID e Nome:

    • sexo (convertido para números: 1 - feminino e 2 - masculino)
    
    • classe (1ª, 2ª, 3ª)
    
    • cônjuges, irmãos (SibSp)
    
    • pais, filhos (Parch)
    
    • idade (substituída pela média dos sobreviventes da classe, quando não informada)

In [40]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
survivors = train[train.Survived == 1]

survivors.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [42]:
survivors.count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [43]:
#idade: substituir NA pela média de idade da classe correspondente
medias = survivors.groupby('Pclass').median().reset_index()

idade_media = medias['Age']
idade_media.index = medias['Pclass']

medias

Pclass  PassengerId  Survived   Age  SibSp  Parch     Fare
0       1        510.5       1.0  35.0    0.0    0.0  77.9583
1       2        441.0       1.0  28.0    0.0    0.0  21.0000
2       3        359.0       1.0  22.0    0.0    0.0   8.5167

In [44]:
def tratar_dados(dataframe, idade_media):
    #sexo: 1 - feminino; 2 - masculino
    dataframe.loc[:, 'Sex'] = dataframe.Sex.apply(lambda s: 1 if s == 'female' else 2)
    
    #idade: substituir NA pela média de idade da classe correspondente    
    for i in range(1, 4):
        dataframe.loc[dataframe.Pclass == i, 'Age'] = dataframe.loc[dataframe.Pclass == i, 'Age'].fillna(idade_media[i])
    
    return dataframe

In [45]:
tratar_dados(survivors, idade_media)

survivors.count()

C:\Users\davir\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            342
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [46]:
dataset = train.copy()

tratar_dados(dataset, idade_media)

dataset.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [47]:
colunas = ['Sex', 'Age', 'SibSp', 'Parch', 'Pclass', 'Survived']

model = GaussianNB()

data = dataset.loc[:500, colunas[:5]]
target = dataset.loc[:500, colunas[5]]
        
model.fit(data, target)

data = dataset.loc[501:, colunas[:5]]
target = dataset.loc[501:, colunas[5]]

predicted = model.predict(data)

print(metrics.classification_report(target, predicted))
print(metrics.confusion_matrix(target, predicted))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       241
           1       0.77      0.64      0.70       149

   micro avg       0.79      0.79      0.79       390
   macro avg       0.79      0.76      0.77       390
weighted avg       0.79      0.79      0.79       390

[[213  28]
 [ 54  95]]


In [48]:
k = 17
i = 1

print(f'{k} folds\n\n')

kfold = KFold(n_splits = k, shuffle = False)

for i_train, i_test in kfold.split(dataset):
    data = dataset.loc[i_train, colunas[:5]]
    target = dataset.loc[i_train, colunas[5]]
        
    model.fit(data, target)
    
    data = dataset.loc[i_test, colunas[:5]]
    target = dataset.loc[i_test, colunas[5]]
    
    predicted = model.predict(data)
    
    print(f'\n\nFold #{i} | train: {len(dataset.iloc[i_train])}, test: {len(dataset.iloc[i_test])}')
    print(metrics.classification_report(target, predicted))
    print(metrics.confusion_matrix(target, predicted))
    
    i += 1

17 folds




Fold #1 | train: 838, test: 53
              precision    recall  f1-score   support

           0       0.85      0.73      0.79        30
           1       0.70      0.83      0.76        23

   micro avg       0.77      0.77      0.77        53
   macro avg       0.77      0.78      0.77        53
weighted avg       0.78      0.77      0.77        53

[[22  8]
 [ 4 19]]


Fold #2 | train: 838, test: 53
              precision    recall  f1-score   support

           0       0.79      0.77      0.78        35
           1       0.58      0.61      0.59        18

   micro avg       0.72      0.72      0.72        53
   macro avg       0.69      0.69      0.69        53
weighted avg       0.72      0.72      0.72        53

[[27  8]
 [ 7 11]]


Fold #3 | train: 838, test: 53
              precision    recall  f1-score   support

           0       0.87      0.69      0.77        39
           1       0.45      0.71      0.56        14

   micro avg       0.70      0.70 

In [49]:
dataset = test.copy()

tratar_dados(dataset, idade_media)

dataset.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    2   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    2   
3          895       3                              Wirz, Mr. Albert    2   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [50]:
data = dataset.loc[:, colunas[:5]]

predicted = model.predict(data)

predicted

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [51]:
test['Survived'] = predicted

test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [52]:
result = test.loc[:, ('PassengerId', 'Survived')]
result.to_csv("gender_submission.csv", sep = ",", index = False)
result

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         1
404         1296         0
405         1297         0
406         1298         0
407         1299         1
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

#### Resultado
 
 0.75598

### Teste 5

Naive Bayes

Utilizando todos os atributos, exceto ID e Nome:

    • sexo (convertido para números: 1 - feminino e 2 - masculino)
    
    • classe (1ª, 2ª, 3ª)
    
    • cônjuges, irmãos (SibSp)
    
    • pais, filhos (Parch)
    
    • idade (substituída pela moda dos sobreviventes da classe, quando não informada)

In [53]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [54]:
survivors = train[train.Survived == 1]

survivors.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [55]:
survivors.count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [56]:
#idade: substituir NA pela moda de idade da classe correspondente
idade_moda = np.empty([4, 1], dtype = float)

for i in range(1, 4):
    idade_moda[i] = survivors.loc[survivors.Pclass == i, 'Age'].mode()
    print(f'Pclass = {i} | Moda da idade = {float(idade_moda[i])}')

Pclass = 1 | Moda da idade = 35.0
Pclass = 2 | Moda da idade = 24.0
Pclass = 3 | Moda da idade = 27.0


In [57]:
def tratar_dados(dataframe, idade_moda):
    #sexo: 1 - feminino; 2 - masculino
    dataframe.loc[:, 'Sex'] = dataframe.Sex.apply(lambda s: 1 if s == 'female' else 2)
    
    #idade: substituir NA pela moda de idade da classe correspondente    
    for i in range(1, 4):
        dataframe.loc[dataframe.Pclass == i, 'Age'] = dataframe.loc[dataframe.Pclass == i, 'Age'].fillna(float(idade_moda[i]))
    
    return dataframe

In [58]:
tratar_dados(survivors, idade_moda)

survivors.count()

C:\Users\davir\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            342
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [59]:
dataset = train.copy()

tratar_dados(dataset, idade_media)

dataset.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [60]:
colunas = ['Sex', 'Age', 'SibSp', 'Parch', 'Pclass', 'Survived']

model = GaussianNB()

data = dataset.loc[:700, colunas[:5]]
target = dataset.loc[:700, colunas[5]]
        
model.fit(data, target)

data = dataset.loc[701:, colunas[:5]]
target = dataset.loc[701:, colunas[5]]

predicted = model.predict(data)

print(metrics.classification_report(target, predicted))
print(metrics.confusion_matrix(target, predicted))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86       120
           1       0.79      0.66      0.72        70

   micro avg       0.81      0.81      0.81       190
   macro avg       0.81      0.78      0.79       190
weighted avg       0.81      0.81      0.81       190

[[108  12]
 [ 24  46]]


In [61]:
k = 5
i = 1

print(f'{k} folds\n\n')

kfold = KFold(n_splits = k, shuffle = False)

for i_train, i_test in kfold.split(dataset):
    data = dataset.loc[i_train, colunas[:5]]
    target = dataset.loc[i_train, colunas[5]]
        
    model.fit(data, target)
    
    data = dataset.loc[i_test, colunas[:5]]
    target = dataset.loc[i_test, colunas[5]]
    
    predicted = model.predict(data)
    
    print(f'\n\nFold #{i} | train: {len(dataset.iloc[i_train])}, test: {len(dataset.iloc[i_test])}')
    print(metrics.classification_report(target, predicted))
    print(metrics.confusion_matrix(target, predicted))
    
    i += 1

5 folds




Fold #1 | train: 712, test: 179
              precision    recall  f1-score   support

           0       0.84      0.72      0.77       120
           1       0.56      0.73      0.63        59

   micro avg       0.72      0.72      0.72       179
   macro avg       0.70      0.72      0.70       179
weighted avg       0.75      0.72      0.73       179

[[86 34]
 [16 43]]


Fold #2 | train: 713, test: 178
              precision    recall  f1-score   support

           0       0.79      0.76      0.77        99
           1       0.71      0.75      0.73        79

   micro avg       0.75      0.75      0.75       178
   macro avg       0.75      0.75      0.75       178
weighted avg       0.75      0.75      0.75       178

[[75 24]
 [20 59]]


Fold #3 | train: 713, test: 178
              precision    recall  f1-score   support

           0       0.88      0.74      0.81       109
           1       0.67      0.84      0.75        69

   micro avg       0.78      0.7

In [62]:
dataset = test.copy()

tratar_dados(dataset, idade_media)

dataset.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    2   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    2   
3          895       3                              Wirz, Mr. Albert    2   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [63]:
data = dataset.loc[:, colunas[:5]]

predicted = model.predict(data)

predicted

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [64]:
test['Survived'] = predicted

test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [65]:
result = test.loc[:, ('PassengerId', 'Survived')]
result.to_csv("gender_submission.csv", sep = ",", index = False)
result

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         1
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

#### Resultado

0.76555